Resources:
  WorkshopRepoE6F95803:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: Infrarepo
    Metadata:
      'aws:cdk:path': PipelineStack/WorkshopRepo/Resource
  WorkshopRepoPipelineStackPipeline9DB740AFEventRule02041222:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        resources:
          - !GetAtt 
            - WorkshopRepoE6F95803
            - Arn
        detail-type:
          - CodeCommit Repository State Change
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceName:
            - master
      State: ENABLED
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:'
              - !Ref 'AWS::Partition'
              - ':codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref PipelineC660917D
          Id: Target0
          RoleArn: !GetAtt 
            - PipelineEventsRole46BEEA7C
            - Arn
    Metadata:
      'aws:cdk:path': >-
        PipelineStack/WorkshopRepo/PipelineStackPipeline9DB740AFEventRule/Resource
  PipelineArtifactsBucketEncryptionKey01D58D69:
    Type: 'AWS::KMS::Key'
    Properties:
      KeyPolicy:
        Statement:
          - Action: 'kms:*'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Resource: '*'
        Version: 2012-10-17
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/ArtifactsBucketEncryptionKey/Resource
  PipelineArtifactsBucketEncryptionKeyAlias5C510EEE:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/codepipeline-pipelinestackpipeline9db740af
      TargetKeyId: !GetAtt 
        - PipelineArtifactsBucketEncryptionKey01D58D69
        - Arn
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/ArtifactsBucketEncryptionKeyAlias/Resource
  PipelineArtifactsBucket22248F97:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt 
                - PipelineArtifactsBucketEncryptionKey01D58D69
                - Arn
              SSEAlgorithm: 'aws:kms'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/ArtifactsBucket/Resource
  PipelineArtifactsBucketPolicyD4F9712A:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PipelineArtifactsBucket22248F97
      PolicyDocument:
        Statement:
          - Action: 's3:*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt 
                - PipelineArtifactsBucket22248F97
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - PipelineArtifactsBucket22248F97
                    - Arn
                  - /*
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/ArtifactsBucket/Policy/Resource
  PipelineRoleD68726F7:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/Role/Resource
  PipelineRoleDefaultPolicyC7A05455:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:Abort*'
              - 's3:DeleteObject*'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:List*'
              - 's3:PutObject'
              - 's3:PutObjectLegalHold'
              - 's3:PutObjectRetention'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
            Effect: Allow
            Resource:
              - !GetAtt 
                - PipelineArtifactsBucket22248F97
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - PipelineArtifactsBucket22248F97
                    - Arn
                  - /*
          - Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:GenerateDataKey*'
              - 'kms:ReEncrypt*'
            Effect: Allow
            Resource: !GetAtt 
              - PipelineArtifactsBucketEncryptionKey01D58D69
              - Arn
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Resource:
              - !GetAtt 
                - PipelineSourceCodePipelineActionRoleC6F9E7F5
                - Arn
              - !GetAtt 
                - PipelinebuildCodePipelineActionRole11BCD4FF
                - Arn
        Version: 2012-10-17
      PolicyName: PipelineRoleDefaultPolicyC7A05455
      Roles:
        - !Ref PipelineRoleD68726F7
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/Role/DefaultPolicy/Resource
  PipelineC660917D:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt 
        - PipelineRoleD68726F7
        - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: !GetAtt 
                  - WorkshopRepoE6F95803
                  - Name
                BranchName: master
                PollForSourceChanges: false
              Name: Source
              OutputArtifacts:
                - Name: Artifact_Source_Source
              RoleArn: !GetAtt 
                - PipelineSourceCodePipelineActionRoleC6F9E7F5
                - Arn
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref BuildProject097C5DB7
              InputArtifacts:
                - Name: Artifact_Source_Source
              Name: build
              OutputArtifacts:
                - Name: Artifact_build_build
              RoleArn: !GetAtt 
                - PipelinebuildCodePipelineActionRole11BCD4FF
                - Arn
              RunOrder: 1
          Name: build
      ArtifactStore:
        EncryptionKey:
          Id: !GetAtt 
            - PipelineArtifactsBucketEncryptionKey01D58D69
            - Arn
          Type: KMS
        Location: !Ref PipelineArtifactsBucket22248F97
        Type: S3
      Name: Infrapipeline
    DependsOn:
      - PipelineRoleDefaultPolicyC7A05455
      - PipelineRoleD68726F7
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/Resource
  PipelineSourceCodePipelineActionRoleC6F9E7F5:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/Source/Source/CodePipelineActionRole/Resource
  PipelineSourceCodePipelineActionRoleDefaultPolicy2D565925:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:Abort*'
              - 's3:DeleteObject*'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:List*'
              - 's3:PutObject'
              - 's3:PutObjectLegalHold'
              - 's3:PutObjectRetention'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
            Effect: Allow
            Resource:
              - !GetAtt 
                - PipelineArtifactsBucket22248F97
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - PipelineArtifactsBucket22248F97
                    - Arn
                  - /*
          - Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:GenerateDataKey*'
              - 'kms:ReEncrypt*'
            Effect: Allow
            Resource: !GetAtt 
              - PipelineArtifactsBucketEncryptionKey01D58D69
              - Arn
          - Action:
              - 'codecommit:CancelUploadArchive'
              - 'codecommit:GetBranch'
              - 'codecommit:GetCommit'
              - 'codecommit:GetUploadArchiveStatus'
              - 'codecommit:UploadArchive'
            Effect: Allow
            Resource: !GetAtt 
              - WorkshopRepoE6F95803
              - Arn
        Version: 2012-10-17
      PolicyName: PipelineSourceCodePipelineActionRoleDefaultPolicy2D565925
      Roles:
        - !Ref PipelineSourceCodePipelineActionRoleC6F9E7F5
    Metadata:
      'aws:cdk:path': >-
        PipelineStack/Pipeline/Source/Source/CodePipelineActionRole/DefaultPolicy/Resource
  PipelineEventsRole46BEEA7C:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/EventsRole/Resource
  PipelineEventsRoleDefaultPolicyFF4FCCE0:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'codepipeline:StartPipelineExecution'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:'
                - !Ref 'AWS::Partition'
                - ':codepipeline:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':'
                - !Ref PipelineC660917D
        Version: 2012-10-17
      PolicyName: PipelineEventsRoleDefaultPolicyFF4FCCE0
      Roles:
        - !Ref PipelineEventsRole46BEEA7C
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/EventsRole/DefaultPolicy/Resource
  PipelinebuildCodePipelineActionRole11BCD4FF:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': PipelineStack/Pipeline/build/build/CodePipelineActionRole/Resource
  PipelinebuildCodePipelineActionRoleDefaultPolicyDC80DBC3:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
              - 'codebuild:StopBuild'
            Effect: Allow
            Resource: !GetAtt 
              - BuildProject097C5DB7
              - Arn
        Version: 2012-10-17
      PolicyName: PipelinebuildCodePipelineActionRoleDefaultPolicyDC80DBC3
      Roles:
        - !Ref PipelinebuildCodePipelineActionRole11BCD4FF
    Metadata:
      'aws:cdk:path': >-
        PipelineStack/Pipeline/build/build/CodePipelineActionRole/DefaultPolicy/Resource
  BuildProjectRoleAA92C755:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: 2012-10-17
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  BuildProjectRoleDefaultPolicy3E9F248C:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource:
              - !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':logs:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':log-group:/aws/codebuild/'
                  - !Ref BuildProject097C5DB7
                  - ':*'
              - !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':logs:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':log-group:/aws/codebuild/'
                  - !Ref BuildProject097C5DB7
          - Action:
              - 'codebuild:BatchPutCodeCoverages'
              - 'codebuild:BatchPutTestCases'
              - 'codebuild:CreateReport'
              - 'codebuild:CreateReportGroup'
              - 'codebuild:UpdateReport'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:'
                - !Ref 'AWS::Partition'
                - ':codebuild:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':report-group/'
                - !Ref BuildProject097C5DB7
                - '-*'
          - Action:
              - 's3:Abort*'
              - 's3:DeleteObject*'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:List*'
              - 's3:PutObject'
              - 's3:PutObjectLegalHold'
              - 's3:PutObjectRetention'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
            Effect: Allow
            Resource:
              - !GetAtt 
                - PipelineArtifactsBucket22248F97
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - PipelineArtifactsBucket22248F97
                    - Arn
                  - /*
          - Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:GenerateDataKey*'
              - 'kms:ReEncrypt*'
            Effect: Allow
            Resource: !GetAtt 
              - PipelineArtifactsBucketEncryptionKey01D58D69
              - Arn
        Version: 2012-10-17
      PolicyName: BuildProjectRoleDefaultPolicy3E9F248C
      Roles:
        - !Ref BuildProjectRoleAA92C755
    Metadata:
      'aws:cdk:path': PipelineStack/BuildProject/Role/DefaultPolicy/Resource
  BuildProject097C5DB7:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:5.0'
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt 
        - BuildProjectRoleAA92C755
        - Arn
      Source:
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      EncryptionKey: !GetAtt 
        - PipelineArtifactsBucketEncryptionKey01D58D69
        - Arn